# Generated by Django 5.1.1 on 2024-09-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phoneNo',
            field=models.CharField(max_length=20),
        ),
    ]
