# Generated by Django 5.1.1 on 2024-09-27 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_alter_child_childid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('eduMaterialID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('book', 'Book'), ('video', 'Video')], max_length=10)),
                ('filePath', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildEduMaterial',
            fields=[
                ('childEduMaterialID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('accessDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeSpent', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edu_materials', to='user.child')),
                ('eduMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edu_materials', to='eduMaterial.educationalmaterial')),
            ],
        ),
    ]
