# Generated by Django 5.1.1 on 2024-09-27 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduMaterial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='filePath',
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='eduMaterialID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
