# Generated by Django 5.1.1 on 2024-09-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduMaterial', '0002_remove_educationalmaterial_filepath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='file',
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
