# Generated by Django 5.1.1 on 2024-09-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduMaterial', '0003_remove_educationalmaterial_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
