# Generated by Django 5.1.1 on 2024-09-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduMaterial', '0005_alter_educationalmaterial_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='file',
        ),
    ]
