# Generated by Django 5.1.1 on 2024-09-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_parent_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
