# Generated by Django 5.1.1 on 2024-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_parent_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
